// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndqcaxsbldeokaglcckm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcWNheHNibGRlb2thZ2xjY2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjAwNTMsImV4cCI6MjA3MTE5NjA1M30.dykXBIaO78bZWJgD_s2eZJAS3zJ_cwAoxLe7v8ovs0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});